export interface GlossaryTerm {
  slug: string;
  term: string;
  shortDefinition: string;
  definition: string;
  relatedTerms: string[];
  relatedPages: { label: string; href: string }[];
}

export const glossaryTerms: GlossaryTerm[] = [
  {
    slug: 'conversion-rate',
    term: 'Conversion Rate',
    shortDefinition: 'The percentage of website visitors who complete a desired action.',
    definition: 'Conversion rate is the percentage of website visitors who complete a desired action — such as filling out a contact form, making a purchase, or booking an appointment. It is calculated by dividing conversions by total visitors and multiplying by 100. A typical business website conversion rate is 2–5%. High-performing conversion-optimised sites can reach 10%+.',
    relatedTerms: ['cta', 'landing-page', 'bounce-rate', 'split-testing'],
    relatedPages: [{ label: 'Conversion-First Design', href: '/concepts/conversion-first-design' }],
  },
  {
    slug: 'core-web-vitals',
    term: 'Core Web Vitals',
    shortDefinition: 'Google\'s three key metrics for measuring page experience: LCP, INP, and CLS.',
    definition: 'Core Web Vitals are a set of real-world performance metrics defined by Google that measure the user experience of a web page. The three metrics are: Largest Contentful Paint (LCP), which measures loading speed; Interaction to Next Paint (INP), which measures interactivity; and Cumulative Layout Shift (CLS), which measures visual stability. Google uses Core Web Vitals as a ranking signal.',
    relatedTerms: ['page-speed', 'lcp', 'cls'],
    relatedPages: [{ label: 'Core Web Vitals Explained', href: '/concepts/core-web-vitals-explained' }, { label: 'How to Speed Up a Slow Website', href: '/answers/how-to-speed-up-a-slow-website' }],
  },
  {
    slug: 'bounce-rate',
    term: 'Bounce Rate',
    shortDefinition: 'The percentage of visitors who leave after viewing only one page.',
    definition: 'Bounce rate is the percentage of sessions in which a user leaves a website after viewing only one page without taking any action. A high bounce rate (above 70%) can indicate poor user experience, slow load times, irrelevant content, or a mismatch between the page and what the user expected. A low bounce rate suggests visitors are engaging with your content. Industry average bounce rates vary: blogs typically see 70–90%, service businesses 40–60%.',
    relatedTerms: ['conversion-rate', 'page-speed', 'ux-design'],
    relatedPages: [{ label: 'How to Reduce Bounce Rate', href: '/answers/how-to-reduce-bounce-rate' }],
  },
  {
    slug: 'above-the-fold',
    term: 'Above the Fold',
    shortDefinition: 'The portion of a web page visible without scrolling.',
    definition: 'Above the fold refers to the portion of a web page that is visible to a user without scrolling. The term originates from newspaper publishing, where the most important stories appeared on the top half of a folded broadsheet. In web design, the above-the-fold area is critical for capturing attention, communicating value, and driving conversions. Effective above-the-fold sections include a clear headline, sub-heading, and a primary call-to-action.',
    relatedTerms: ['hero-section', 'cta', 'conversion-rate'],
    relatedPages: [{ label: 'Above the Fold Design', href: '/concepts/above-the-fold-design' }],
  },
  {
    slug: 'cta',
    term: 'Call-to-Action (CTA)',
    shortDefinition: 'A design element that directs users to take a specific action.',
    definition: 'A call-to-action (CTA) is a prompt — usually a button, link, or form — that directs a website visitor to take a specific action. Common examples include "Get a Free Quote", "Book a Call", "Download the Guide", or "Start Your Free Trial". Effective CTAs are clear, action-oriented, and positioned prominently in the user\'s flow. The number and placement of CTAs significantly impacts conversion rate.',
    relatedTerms: ['conversion-rate', 'landing-page', 'hero-section'],
    relatedPages: [{ label: 'What Should a Homepage Include', href: '/answers/what-should-a-homepage-include' }],
  },
  {
    slug: 'ux-design',
    term: 'UX Design',
    shortDefinition: 'The process of designing products that are useful, usable, and enjoyable.',
    definition: 'User Experience (UX) design is the process of creating products that provide meaningful, relevant, and enjoyable experiences to users. In web design, UX design covers information architecture, user flows, wireframing, usability testing, and the overall journey from first visit to conversion. Good UX design reduces friction, guides users toward goals, and increases customer satisfaction. UX design is distinct from UI design, which focuses on the visual interface.',
    relatedTerms: ['ui-design', 'wireframe', 'conversion-rate'],
    relatedPages: [{ label: 'What is UI/UX Design', href: '/answers/what-is-ui-ux-design' }],
  },
  {
    slug: 'ui-design',
    term: 'UI Design',
    shortDefinition: 'The design of the visual elements users interact with on a screen.',
    definition: 'User Interface (UI) design is the craft of designing the visual elements that users interact with on a digital product — buttons, icons, typography, colours, spacing, and layout. Good UI design is visually appealing, consistent, and aligned with the brand. UI design works alongside UX design: UX determines what needs to exist and why; UI determines how it looks and feels.',
    relatedTerms: ['ux-design', 'wireframe', 'white-space'],
    relatedPages: [{ label: 'What is UI/UX Design', href: '/answers/what-is-ui-ux-design' }],
  },
  {
    slug: 'seo',
    term: 'SEO (Search Engine Optimisation)',
    shortDefinition: 'The practice of improving a website\'s visibility in search engine results.',
    definition: 'Search Engine Optimisation (SEO) is the practice of improving a website\'s visibility in organic (non-paid) search engine results. SEO covers three main areas: technical SEO (site speed, crawlability, structured data), on-page SEO (content, headings, meta tags), and off-page SEO (backlinks, authority). For local businesses, local SEO — optimising for location-based searches — is particularly important.',
    relatedTerms: ['schema-markup', 'meta-description', 'sitemap', 'page-speed'],
    relatedPages: [{ label: 'Do I Need SEO?', href: '/answers/do-i-need-seo' }, { label: 'What is Technical SEO', href: '/answers/what-is-technical-seo' }],
  },
  {
    slug: 'page-speed',
    term: 'Page Speed',
    shortDefinition: 'How quickly a web page loads and becomes interactive.',
    definition: 'Page speed refers to how quickly a web page loads, renders, and becomes interactive for a user. It is measured by Google PageSpeed Insights using a 0–100 scoring system. Scores above 90 are considered "Good". Page speed affects user experience, conversion rate (each second of delay reduces conversions by ~7%), and SEO rankings. Key factors affecting page speed include image optimisation, JavaScript execution, server response time, and code efficiency.',
    relatedTerms: ['core-web-vitals', 'bounce-rate', 'next-js'],
    relatedPages: [{ label: 'What is a Good PageSpeed Score?', href: '/answers/what-is-a-good-pagespeed-score' }, { label: 'How to Speed Up a Slow Website', href: '/answers/how-to-speed-up-a-slow-website' }],
  },
  {
    slug: 'responsive-design',
    term: 'Responsive Design',
    shortDefinition: 'A design approach where layout adapts to different screen sizes.',
    definition: 'Responsive web design is an approach where a website\'s layout, images, and content adapt fluidly to different screen sizes and orientations — desktop, tablet, and mobile. A responsive site uses flexible grids, fluid images, and CSS media queries to provide an optimal viewing experience on every device. With over 60% of web traffic coming from mobile devices, responsive design is a baseline requirement, not an optional feature.',
    relatedTerms: ['mobile-first', 'ux-design', 'core-web-vitals'],
    relatedPages: [{ label: 'What is Responsive Design?', href: '/answers/what-is-responsive-design' }],
  },
  {
    slug: 'wireframe',
    term: 'Wireframe',
    shortDefinition: 'A low-fidelity blueprint of a web page\'s layout and structure.',
    definition: 'A wireframe is a low-fidelity, schematic representation of a web page that outlines the structure, layout, and content hierarchy without visual design details like colours or fonts. Wireframes are used in the early stages of the design process to plan information architecture, user flows, and page structure. They allow for rapid iteration and stakeholder feedback before expensive visual design work begins.',
    relatedTerms: ['ux-design', 'ui-design', 'site-architecture'],
    relatedPages: [{ label: 'Our Design Process', href: '/about' }],
  },
  {
    slug: 'landing-page',
    term: 'Landing Page',
    shortDefinition: 'A standalone page designed specifically to convert visitors.',
    definition: 'A landing page is a standalone web page designed with a single, focused conversion goal — such as generating leads, selling a product, or collecting email sign-ups. Unlike homepage or service pages, landing pages eliminate distractions (no navigation, no footer links) and direct all visitor attention toward one action. High-converting landing pages have a clear value proposition, social proof, and a prominent call-to-action.',
    relatedTerms: ['conversion-rate', 'cta', 'lead-generation', 'split-testing'],
    relatedPages: [{ label: 'What is a Landing Page?', href: '/answers/what-is-a-landing-page' }],
  },
  {
    slug: 'split-testing',
    term: 'Split Testing (A/B Testing)',
    shortDefinition: 'Testing two versions of a page to see which performs better.',
    definition: 'Split testing, also called A/B testing, is the practice of comparing two versions of a web page (or element) to determine which one achieves a better outcome. One group of visitors sees version A, another sees version B, and performance is measured against a defined goal (e.g., form submissions, clicks, purchases). Split testing removes guesswork and enables data-driven design decisions.',
    relatedTerms: ['conversion-rate', 'landing-page', 'heat-map'],
    relatedPages: [{ label: 'How to Measure Website Success', href: '/answers/how-to-measure-website-success' }],
  },
  {
    slug: 'schema-markup',
    term: 'Schema Markup',
    shortDefinition: 'Structured data code that helps search engines understand your content.',
    definition: 'Schema markup is structured data added to a web page\'s HTML using JSON-LD (or other formats) that provides additional context to search engines about the content on the page. It uses the Schema.org vocabulary and can describe businesses, articles, FAQs, products, events, reviews, and more. Schema markup can trigger rich results in Google Search, such as star ratings, FAQ dropdowns, and breadcrumbs, which increase click-through rates.',
    relatedTerms: ['seo', 'structured-data', 'sitemap'],
    relatedPages: [{ label: 'Schema Markup for Small Business', href: '/concepts/schema-markup-for-small-business' }],
  },
  {
    slug: 'meta-description',
    term: 'Meta Description',
    shortDefinition: 'A 150–160 character summary of a page shown in search results.',
    definition: 'A meta description is an HTML attribute that provides a short summary (typically 150–160 characters) of a web page\'s content. It appears under the page title in search engine results pages (SERPs). While meta descriptions are not a direct Google ranking factor, they significantly influence click-through rate from search results. Effective meta descriptions include the target keyword, communicate the page\'s value, and contain a clear call-to-action.',
    relatedTerms: ['seo', 'sitemap', 'schema-markup'],
    relatedPages: [{ label: 'What is Technical SEO?', href: '/answers/what-is-technical-seo' }],
  },
  {
    slug: 'sitemap',
    term: 'Sitemap',
    shortDefinition: 'A file listing all the pages on a website for search engines.',
    definition: 'A sitemap is a file (usually XML) that lists all the pages, posts, and media on a website and provides metadata about each URL (last modified date, priority, change frequency). Sitemaps help search engine crawlers discover and index your content efficiently. All websites should have a sitemap.xml file submitted to Google Search Console. Next.js can generate sitemaps automatically.',
    relatedTerms: ['seo', 'robots-txt', 'schema-markup'],
    relatedPages: [{ label: 'What is Technical SEO?', href: '/answers/what-is-technical-seo' }],
  },
  {
    slug: 'breadcrumbs',
    term: 'Breadcrumbs',
    shortDefinition: 'Navigation links showing a user\'s location within a website hierarchy.',
    definition: 'Breadcrumbs are a secondary navigation element that shows users their current location within a website\'s hierarchy. For example: Home > Services > Web Design for Restaurants. Breadcrumbs improve user experience by making navigation clearer, and they improve SEO by helping search engines understand site structure. When implemented with BreadcrumbList schema markup, they appear directly in Google search results.',
    relatedTerms: ['seo', 'site-architecture', 'ux-design'],
    relatedPages: [{ label: 'Site Architecture', href: '/concepts/site-architecture' }],
  },
  {
    slug: 'internal-linking',
    term: 'Internal Linking',
    shortDefinition: 'Links between pages on the same website.',
    definition: 'Internal linking refers to hyperlinks that point from one page on a website to another page on the same website. Internal links help users navigate between related content, distribute "link equity" across the site, and help search engine crawlers discover and index all your pages. A well-structured internal link architecture can significantly improve both user experience and SEO performance.',
    relatedTerms: ['seo', 'site-architecture', 'breadcrumbs'],
    relatedPages: [{ label: 'Site Architecture', href: '/concepts/site-architecture' }],
  },
  {
    slug: 'lead-generation',
    term: 'Lead Generation',
    shortDefinition: 'The process of attracting and converting website visitors into potential customers.',
    definition: 'Lead generation is the process of attracting visitors to your website and converting them into potential customers (leads) by capturing their contact information or encouraging them to make an enquiry. Web-based lead generation uses tactics such as contact forms, live chat, free downloads, consultations, and email sign-ups. Effective lead generation design addresses objections, builds trust, and makes the next step obvious.',
    relatedTerms: ['conversion-rate', 'cta', 'landing-page', 'social-proof'],
    relatedPages: [{ label: 'Lead Generation Through Web Design', href: '/concepts/lead-generation-through-web-design' }, { label: 'How to Get More Leads From Your Website', href: '/answers/how-to-get-more-leads-from-your-website' }],
  },
  {
    slug: 'social-proof',
    term: 'Social Proof',
    shortDefinition: 'Evidence that other people trust and value your business.',
    definition: 'Social proof is a psychological principle and a web design pattern where evidence of other people\'s trust or satisfaction is used to influence visitor behaviour. Types of social proof in web design include: testimonials and reviews, case studies, client logos, ratings (e.g., Google star ratings), media mentions, and usage statistics. Social proof reduces perceived risk and increases confidence in making a purchase or enquiry.',
    relatedTerms: ['conversion-rate', 'lead-generation', 'cta'],
    relatedPages: [{ label: 'Trust Engineering', href: '/concepts/trust-engineering' }],
  },
  {
    slug: 'white-space',
    term: 'White Space',
    shortDefinition: 'Empty space between elements that improves readability and focus.',
    definition: 'White space (also called negative space) refers to the empty areas between design elements on a web page — between paragraphs, around images, inside buttons, and between sections. Despite feeling counter-intuitive, generous white space improves readability (by reducing cognitive load), guides attention, and creates a sense of quality and professionalism. Sites with cramped layouts tend to feel overwhelming; well-spaced layouts feel premium.',
    relatedTerms: ['ui-design', 'ux-design', 'hero-section'],
    relatedPages: [],
  },
  {
    slug: 'hero-section',
    term: 'Hero Section',
    shortDefinition: 'The prominent top section of a webpage, designed to capture attention immediately.',
    definition: 'The hero section is the top prominent section of a webpage — the first thing visitors see when the page loads. It typically contains a headline, sub-headline, supporting image or video, and a primary call-to-action. The hero section has the highest impact on conversion rates because it determines whether a visitor stays or leaves. An effective hero section communicates a clear value proposition and answers "why should I stay here?" within 3–5 seconds.',
    relatedTerms: ['above-the-fold', 'cta', 'conversion-rate'],
    relatedPages: [{ label: 'What Should a Homepage Include?', href: '/answers/what-should-a-homepage-include' }],
  },
  {
    slug: 'mobile-first',
    term: 'Mobile-First',
    shortDefinition: 'A design approach that starts with mobile screens before scaling to desktop.',
    definition: 'Mobile-first is a design and development philosophy that starts the design process with the smallest screen size (mobile) and then progressively enhances the experience for larger screens (tablet, desktop). It is the opposite of the traditional approach where desktop designs were scaled down to mobile. Mobile-first ensures the core experience is optimised for the majority of users — over 60% of web traffic now comes from mobile devices.',
    relatedTerms: ['responsive-design', 'core-web-vitals', 'ux-design'],
    relatedPages: [{ label: 'Mobile-First Approach', href: '/concepts/mobile-first-approach' }],
  },
  {
    slug: 'next-js',
    term: 'Next.js',
    shortDefinition: 'A React framework for building high-performance, SEO-friendly websites.',
    definition: 'Next.js is an open-source React framework built by Vercel for creating server-side rendered (SSR) and statically generated websites and web applications. Next.js is the technology stack of choice for high-performance business websites because it offers built-in image optimisation, automatic code splitting, server-side rendering (for SEO), and a file-based routing system. CrftdWeb builds all projects in Next.js.',
    relatedTerms: ['page-speed', 'seo', 'core-web-vitals'],
    relatedPages: [{ label: 'Next.js for Business Websites', href: '/concepts/nextjs-for-business-websites' }, { label: 'WordPress vs Custom-Coded Website', href: '/blog/wordpress-vs-custom-coded-website' }],
  },
  {
    slug: 'heat-map',
    term: 'Heatmap',
    shortDefinition: 'A visual representation of where users click, scroll, and focus on a page.',
    definition: 'A heatmap is a data visualisation tool that shows where users click, scroll, move their mouse, and focus their attention on a web page. Heatmaps are displayed as colour gradations — red/orange for high activity, blue/green for low activity. They provide qualitative insight into user behaviour and are used to identify usability issues, optimise CTAs, and improve page layout. Tools like Hotjar and Microsoft Clarity provide heatmap functionality.',
    relatedTerms: ['ux-design', 'split-testing', 'conversion-rate'],
    relatedPages: [{ label: 'How to Measure Website Success', href: '/answers/how-to-measure-website-success' }],
  },
  {
    slug: 'seo-guide',
    term: 'SEO Guide',
    shortDefinition: 'Search Engine Optimisation — the practice of improving organic search rankings.',
    definition: 'SEO (Search Engine Optimisation) is the process of improving a website\'s visibility in organic (non-paid) search engine results. It encompasses on-page SEO (content, meta tags, schema), technical SEO (site speed, crawlability, structured data), and off-page SEO (backlinks, authority). Good SEO drives sustained, compounding traffic without paid advertising spend.',
    relatedTerms: ['technical-seo', 'schema-markup', 'page-speed', 'meta-description'],
    relatedPages: [{ label: 'Do I Need SEO?', href: '/answers/do-i-need-seo' }, { label: 'What is Technical SEO?', href: '/answers/what-is-technical-seo' }],
  },
  {
    slug: 'technical-seo',
    term: 'Technical SEO',
    shortDefinition: 'The process of optimising the infrastructure of a website for search engine crawling and indexing.',
    definition: 'Technical SEO refers to optimisations that help search engines crawl, index, and rank a website more effectively. It includes site speed (Core Web Vitals), HTTPS security, XML sitemaps, robots.txt, structured data (schema markup), canonical tags, mobile-friendliness, and internal linking structure. Technical SEO forms the foundation that makes all other SEO efforts work.',
    relatedTerms: ['seo', 'schema-markup', 'page-speed', 'sitemap'],
    relatedPages: [{ label: 'What is Technical SEO?', href: '/answers/what-is-technical-seo' }],
  },
  {
    slug: 'schema-markup-guide',
    term: 'Schema Markup Guide',
    shortDefinition: 'Structured data that helps search engines understand your website\'s content.',
    definition: 'Schema markup is a form of structured data (using JSON-LD, Microdata, or RDFa) added to a web page\'s HTML that helps search engines understand the meaning and context of the content. Schema types include Organisation, Product, Article, FAQ, BreadcrumbList, and more. Rich results in Google Search (star ratings, FAQs, breadcrumbs) are powered by schema markup.',
    relatedTerms: ['seo', 'technical-seo', 'json-ld'],
    relatedPages: [{ label: 'Schema Markup for Small Business', href: '/concepts/schema-markup-for-small-business' }],
  },
  {
    slug: 'json-ld',
    term: 'JSON-LD',
    shortDefinition: 'A format for embedding structured data on web pages using JSON notation.',
    definition: 'JSON-LD (JavaScript Object Notation for Linked Data) is a method for encoding structured data on web pages. It uses a <script type="application/ld+json"> tag embedded in the HTML head, making it easy to add schema markup without modifying existing content. Google recommends JSON-LD as the preferred format for structured data because it is easy to implement, maintain, and debug.',
    relatedTerms: ['schema-markup', 'seo', 'technical-seo'],
    relatedPages: [{ label: 'Schema Markup for Small Business', href: '/concepts/schema-markup-for-small-business' }],
  },
  {
    slug: 'xml-sitemap',
    term: 'XML Sitemap',
    shortDefinition: 'A file that lists all pages on a website to help search engines discover and index them.',
    definition: 'An XML sitemap is a file that lists the URLs of all pages on a website. It helps search engines like Google discover, crawl, and index your content more efficiently — especially useful for large sites or pages that don\'t have many incoming internal links. A well-structured sitemap includes the last modified date and priority level for each page. It should be submitted to Google Search Console.',
    relatedTerms: ['seo', 'technical-seo', 'robots-txt'],
    relatedPages: [{ label: 'What is Technical SEO?', href: '/answers/what-is-technical-seo' }],
  },
  {
    slug: 'robots-txt',
    term: 'Robots.txt',
    shortDefinition: 'A file that instructs search engine bots which pages to crawl and index.',
    definition: 'Robots.txt is a text file placed at the root of a website (e.g., example.com/robots.txt) that provides instructions to web crawlers about which pages or sections of the site should not be crawled or indexed. It uses Allow and Disallow directives per user-agent. While compliance is voluntary for legitimate crawlers like Googlebot, it is respected by all major search engines and AI crawlers.',
    relatedTerms: ['seo', 'technical-seo', 'sitemap'],
    relatedPages: [{ label: 'What is Technical SEO?', href: '/answers/what-is-technical-seo' }],
  },
  {
    slug: 'meta-description-guide',
    term: 'Meta Description Guide',
    shortDefinition: 'A 150–160 character summary that appears in search engine results under the page title.',
    definition: 'A meta description is an HTML attribute that provides a concise summary of a web page\'s content. It appears in search engine results pages (SERPs) beneath the page title and URL. While meta descriptions are not a direct ranking factor for Google, they significantly influence click-through rates (CTR) — a well-written meta description can increase organic traffic without improving rankings.',
    relatedTerms: ['seo', 'technical-seo', 'cta'],
    relatedPages: [{ label: 'What Should a Homepage Include?', href: '/answers/what-should-a-homepage-include' }],
  },
  {
    slug: 'page-speed-guide',
    term: 'Page Speed Guide',
    shortDefinition: 'How fast a web page loads and becomes interactive for a user.',
    definition: 'Page speed refers to how quickly a web page loads and becomes fully interactive. It is measured by metrics including Time to First Byte (TTFB), First Contentful Paint (FCP), Largest Contentful Paint (LCP), and Time to Interactive (TTI). Page speed is a direct Google ranking factor and a major determinant of user experience — a 1-second delay in load time reduces conversions by 7%.',
    relatedTerms: ['core-web-vitals', 'lcp', 'technical-seo'],
    relatedPages: [{ label: 'How to Speed Up a Slow Website', href: '/answers/how-to-speed-up-a-slow-website' }, { label: 'What is a Good PageSpeed Score?', href: '/answers/what-is-a-good-pagespeed-score' }],
  },
  {
    slug: 'lcp',
    term: 'LCP (Largest Contentful Paint)',
    shortDefinition: 'A Core Web Vital that measures how quickly the largest content element loads.',
    definition: 'Largest Contentful Paint (LCP) is a Core Web Vital that measures the time it takes for the largest visible content element (usually an image or text block) on a page to load. Google\'s threshold for a "Good" LCP is under 2.5 seconds. A poor LCP is typically caused by slow server response times, render-blocking JavaScript, slow image loading, or client-side rendering delays.',
    relatedTerms: ['core-web-vitals', 'page-speed', 'cls'],
    relatedPages: [{ label: 'Core Web Vitals Explained', href: '/concepts/core-web-vitals-explained' }],
  },
  {
    slug: 'cls',
    term: 'CLS (Cumulative Layout Shift)',
    shortDefinition: 'A Core Web Vital that measures how much the page layout shifts while loading.',
    definition: 'Cumulative Layout Shift (CLS) is a Core Web Vital that measures visual stability — how much the layout unexpectedly shifts during page load. Each shift is scored by its impact fraction and distance fraction. Google\'s "Good" threshold is a CLS score below 0.1. Common causes of high CLS include images without defined dimensions, ads that load dynamically, and web fonts causing FOIT/FOUT.',
    relatedTerms: ['core-web-vitals', 'lcp', 'page-speed'],
    relatedPages: [{ label: 'Core Web Vitals Explained', href: '/concepts/core-web-vitals-explained' }],
  },
  {
    slug: 'above-fold-content',
    term: 'Above the Fold Content',
    shortDefinition: 'The portion of a web page visible without scrolling.',
    definition: 'Above the fold refers to the portion of a web page that is visible to a user without scrolling. The term originates from newspaper publishing, where the most important stories appeared on the top half of the front page. In web design, above-the-fold content is critical for capturing attention, communicating value, and prompting action. The hero section, headline, subheadline, and primary CTA should all be visible above the fold.',
    relatedTerms: ['hero-section', 'cta', 'ux-design', 'conversion-rate'],
    relatedPages: [{ label: 'What Should a Homepage Include?', href: '/answers/what-should-a-homepage-include' }],
  },
  {
    slug: 'wireframe-design',
    term: 'Wireframe Design',
    shortDefinition: 'A low-fidelity layout sketch that defines the structure of a web page.',
    definition: 'A wireframe is a low-fidelity visual representation of a web page\'s layout and structure. It shows the placement of elements such as navigation, headings, content blocks, images, and CTAs — without visual design details like colour or typography. Wireframes are produced early in the design process to establish information architecture and user flow before investing in full design work.',
    relatedTerms: ['ux-design', 'site-architecture', 'above-the-fold'],
    relatedPages: [{ label: 'Conversion-First Design', href: '/concepts/conversion-first-design' }],
  },
  {
    slug: 'open-graph',
    term: 'Open Graph',
    shortDefinition: 'A protocol that controls how web pages appear when shared on social media.',
    definition: 'Open Graph (OG) is a protocol originally created by Facebook that enables any web page to become a rich object in a social graph. When a URL is shared on platforms like Facebook, LinkedIn, Twitter, or Slack, Open Graph meta tags determine how the preview appears — including the title, description, and image. Correct Open Graph implementation is essential for professional social sharing appearances.',
    relatedTerms: ['meta-description', 'seo', 'schema-markup'],
    relatedPages: [{ label: 'What Should a Homepage Include?', href: '/answers/what-should-a-homepage-include' }],
  },
  {
    slug: 'accessibility',
    term: 'Web Accessibility',
    shortDefinition: 'Designing websites so they can be used by people with disabilities.',
    definition: 'Web accessibility means designing and developing websites so that people with disabilities can perceive, understand, navigate, and interact with them. Accessibility standards are defined by the Web Content Accessibility Guidelines (WCAG). Key considerations include colour contrast ratios, keyboard navigation, alt text for images, ARIA labels, readable font sizes, and logical heading structure. Accessibility also benefits SEO.',
    relatedTerms: ['ux-design', 'mobile-first', 'seo'],
    relatedPages: [{ label: 'Site Architecture', href: '/concepts/site-architecture' }],
  },
  {
    slug: 'ssl-certificate',
    term: 'SSL Certificate',
    shortDefinition: 'A digital certificate that encrypts data between a browser and server (HTTPS).',
    definition: 'An SSL (Secure Sockets Layer) certificate is a digital certificate that authenticates a website\'s identity and enables an encrypted connection using HTTPS protocol. The padlock icon in the browser address bar indicates SSL is active. SSL certificates are a basic requirement for any website — Google flags non-HTTPS sites as insecure, and browsers display warnings to users. They are also a minor ranking factor for Google.',
    relatedTerms: ['technical-seo', 'seo', 'robots-txt'],
    relatedPages: [{ label: 'What is Technical SEO?', href: '/answers/what-is-technical-seo' }],
  },
  {
    slug: 'typography',
    term: 'Typography',
    shortDefinition: 'The art of arranging type to make written language readable and visually appealing.',
    definition: 'Typography in web design refers to the selection and arrangement of typefaces, sizes, line heights, letter spacing, and font weights to make text legible, readable, and visually compelling. Good typography improves readability, establishes brand personality, and guides users through content hierarchy. Key considerations include font pairing, optimal line length (50–75 characters), and system font vs. web font performance trade-offs.',
    relatedTerms: ['ux-design', 'white-space', 'above-the-fold'],
    relatedPages: [{ label: 'Conversion-First Design', href: '/concepts/conversion-first-design' }],
  },
  {
    slug: 'colour-palette',
    term: 'Colour Palette',
    shortDefinition: 'The set of colours used consistently throughout a website\'s design.',
    definition: 'A colour palette in web design is a defined set of colours used consistently across all pages and elements of a website. It typically includes a primary brand colour, secondary accent colour, neutral colours (greys, whites, blacks), and semantic colours for success/error states. A well-defined colour palette creates visual coherence, reinforces brand identity, and supports accessibility through sufficient contrast ratios.',
    relatedTerms: ['ux-design', 'typography', 'white-space'],
    relatedPages: [{ label: 'Conversion-First Design', href: '/concepts/conversion-first-design' }],
  },
  {
    slug: 'internal-linking-guide',
    term: 'Internal Linking Guide',
    shortDefinition: 'Hyperlinks that connect pages within the same website.',
    definition: 'Internal linking refers to hyperlinks that point from one page to another page within the same domain. Internal links serve two main purposes: they help users navigate between related content, and they distribute "link equity" (PageRank) across the site to signal to search engines which pages are most important. A strong internal linking structure improves both SEO and user engagement by guiding visitors to relevant content.',
    relatedTerms: ['seo', 'site-architecture', 'technical-seo'],
    relatedPages: [{ label: 'Site Architecture', href: '/concepts/site-architecture' }],
  },
  {
    slug: 'backlink',
    term: 'Backlink',
    shortDefinition: 'A hyperlink from an external website pointing to your site.',
    definition: 'A backlink (also called an inbound link or external link) is a hyperlink on another website that points to your web page. Backlinks are one of the most important SEO ranking factors — Google interprets a link from a reputable site as a "vote of confidence" in your content. The quality of backlinks (authority of the linking site, relevance, anchor text) matters more than quantity. Building high-quality backlinks is central to off-page SEO.',
    relatedTerms: ['seo', 'domain-authority', 'internal-linking'],
    relatedPages: [{ label: 'Do I Need SEO?', href: '/answers/do-i-need-seo' }],
  },
  {
    slug: 'domain-authority',
    term: 'Domain Authority',
    shortDefinition: 'A metric (by Moz) predicting how likely a site is to rank in search engines.',
    definition: 'Domain Authority (DA) is a search engine ranking score developed by Moz that predicts how likely a website is to rank in search engine results pages, on a scale of 1–100. It is based primarily on the quality and quantity of backlinks pointing to the domain. A higher DA generally correlates with better organic search rankings although Google does not use DA directly — it is a third-party proxy metric for site authority.',
    relatedTerms: ['seo', 'backlink', 'technical-seo'],
    relatedPages: [{ label: 'Do I Need SEO?', href: '/answers/do-i-need-seo' }],
  },
  {
    slug: 'breadcrumb',
    term: 'Breadcrumb Navigation',
    shortDefinition: 'A secondary navigation aid showing the user\'s current location within a website hierarchy.',
    definition: 'Breadcrumb navigation is a secondary navigation element that shows users their current location within a website\'s hierarchy. For example: Home > Services > Web Design for Restaurants. Breadcrumbs improve user experience (allowing quick navigation to parent pages), reduce bounce rate, and are an SEO signal — Google displays breadcrumbs in search results when BreadcrumbList schema is implemented.',
    relatedTerms: ['site-architecture', 'seo', 'ux-design', 'schema-markup'],
    relatedPages: [{ label: 'Site Architecture', href: '/concepts/site-architecture' }],
  },
  {
    slug: 'footer',
    term: 'Footer',
    shortDefinition: 'The bottom section of a web page, typically containing navigation links and legal information.',
    definition: 'The footer is the section at the bottom of a web page that typically contains secondary navigation links, contact information, social media links, legal pages (privacy policy, terms), copyright notice, and sometimes CTAs. A well-designed footer improves navigation (especially for mobile users who scroll to the bottom), consolidates site-wide links for SEO, and reinforces trust signals like certifications or accreditations.',
    relatedTerms: ['site-architecture', 'internal-linking', 'ux-design'],
    relatedPages: [{ label: 'Site Architecture', href: '/concepts/site-architecture' }],
  },
  {
    slug: 'above-fold-optimisation',
    term: 'Above-Fold Optimisation',
    shortDefinition: 'Techniques to ensure the above-fold area loads quickly and converts effectively.',
    definition: 'Above-fold optimisation involves ensuring the visible portion of a page on first load is both fast and conversion-focused. Technically, this means inlining critical CSS, preloading hero images, and deferring below-fold scripts. From a design perspective, it means placing the primary value proposition, headline, and CTA within immediate view. The goal is to reduce initial load time and increase the likelihood of user engagement before any scrolling.',
    relatedTerms: ['above-the-fold', 'page-speed', 'cta', 'lcp'],
    relatedPages: [{ label: 'How to Speed Up a Slow Website', href: '/answers/how-to-speed-up-a-slow-website' }],
  },
  {
    slug: 'analytics',
    term: 'Web Analytics',
    shortDefinition: 'The collection and analysis of data about website visitors and their behaviour.',
    definition: 'Web analytics is the measurement, collection, analysis, and reporting of website data to understand user behaviour and optimise performance. Key metrics include sessions, users, page views, bounce rate, session duration, conversion rate, and goal completions. Google Analytics 4 (GA4) is the most widely used analytics platform. Analytics data informs decisions about content strategy, UX improvements, and marketing investment.',
    relatedTerms: ['conversion-rate', 'bounce-rate', 'split-testing'],
    relatedPages: [{ label: 'How to Measure Website Success', href: '/answers/how-to-measure-website-success' }],
  },
  {
    slug: 'structured-data',
    term: 'Structured Data',
    shortDefinition: 'Standardised formats for providing information about a page and its content to search engines.',
    definition: 'Structured data is a standardised format for providing information about a page and its content to search engines, using schema.org vocabulary. It helps search engines understand the context and meaning of content beyond just the text. When correctly implemented, structured data can unlock rich results in Google Search (FAQs, star ratings, breadcrumbs, how-to steps, product information). JSON-LD is the recommended format for structured data.',
    relatedTerms: ['schema-markup', 'json-ld', 'seo', 'technical-seo'],
    relatedPages: [{ label: 'Schema Markup for Small Business', href: '/concepts/schema-markup-for-small-business' }],
  },
  {
    slug: 'progressive-enhancement',
    term: 'Progressive Enhancement',
    shortDefinition: 'A strategy that builds core functionality first, then enhances for capable browsers.',
    definition: 'Progressive enhancement is a web design strategy that starts with a solid, accessible baseline of HTML and CSS that works in any browser, then adds enhanced features (JavaScript interactions, advanced CSS) for modern browsers that support them. It ensures the core content and functionality are accessible to everyone — regardless of browser capabilities, network speed, or device. It is the opposite of graceful degradation.',
    relatedTerms: ['accessibility', 'mobile-first', 'ux-design'],
    relatedPages: [{ label: 'Mobile-First Approach', href: '/concepts/mobile-first-approach' }],
  },
  {
    slug: 'form-optimisation',
    term: 'Form Optimisation',
    shortDefinition: 'Improving web forms to reduce friction and increase completion rates.',
    definition: 'Form optimisation involves reducing friction in web forms to improve submission rates. Best practices include minimising the number of fields (only ask for what you need), using clear labels and placeholder text, providing inline validation, showing progress for multi-step forms, using appropriate input types on mobile, and offering social login options. Contact form completion rates drop significantly with each additional required field.',
    relatedTerms: ['conversion-rate', 'ux-design', 'cta', 'split-testing'],
    relatedPages: [{ label: 'How to Get More Leads from Your Website', href: '/answers/how-to-get-more-leads-from-your-website' }],
  },
  {
    slug: 'lazy-loading',
    term: 'Lazy Loading',
    shortDefinition: 'A technique that defers loading of non-critical resources until they are needed.',
    definition: 'Lazy loading is a performance optimisation technique that defers the loading of non-critical resources (images, videos, components) until they are about to enter the viewport. Instead of loading all images on page load, lazy loading fetches them only when a user scrolls near them. This reduces initial page weight, improves LCP, and can dramatically reduce bandwidth usage — especially on image-heavy pages.',
    relatedTerms: ['page-speed', 'lcp', 'core-web-vitals'],
    relatedPages: [{ label: 'How to Speed Up a Slow Website', href: '/answers/how-to-speed-up-a-slow-website' }],
  },
  {
    slug: 'cdn',
    term: 'CDN (Content Delivery Network)',
    shortDefinition: 'A distributed network of servers that delivers web content to users from the nearest location.',
    definition: 'A Content Delivery Network (CDN) is a geographically distributed network of servers that caches and delivers web content (images, CSS, JS, videos) from the server closest to the user. CDNs dramatically reduce latency and improve page load times by minimising the physical distance data must travel. Major CDN providers include Cloudflare, Fastly, AWS CloudFront, and Vercel\'s Edge Network. Modern frameworks like Next.js automatically leverage CDN distribution.',
    relatedTerms: ['page-speed', 'lcp', 'next-js'],
    relatedPages: [{ label: 'How to Speed Up a Slow Website', href: '/answers/how-to-speed-up-a-slow-website' }],
  },
  {
    slug: 'trust-signals',
    term: 'Trust Signals',
    shortDefinition: 'Elements that build credibility and reduce perceived risk for website visitors.',
    definition: 'Trust signals are website elements that build credibility, reduce perceived risk, and increase visitor confidence in a business. They include client logos, testimonials and reviews, case studies, certification badges, security indicators (SSL padlock, payment logos), team photos, press mentions, guarantee statements, and transparent pricing. Trust signals are critical for converting visitors on services with high purchase value or perceived risk.',
    relatedTerms: ['social-proof', 'conversion-rate', 'cta'],
    relatedPages: [{ label: 'Trust Engineering', href: '/concepts/trust-engineering' }, { label: 'How to Get More Leads from Your Website', href: '/answers/how-to-get-more-leads-from-your-website' }],
  },
];

export function getTermBySlug(slug: string): GlossaryTerm | undefined {
  return glossaryTerms.find((t) => t.slug === slug);
}

export function getAllTermSlugs(): string[] {
  return glossaryTerms.map((t) => t.slug);
}
